<?php
return array (
  0 => 
  array (
    'typeid' => '61',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '21',
    'name' => '产品',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  1 => 
  array (
    'typeid' => '62',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '22',
    'name' => '服务项目',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  2 => 
  array (
    'typeid' => '65',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '25',
    'name' => '知识指导',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  3 => 
  array (
    'typeid' => '80',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '40',
    'name' => '合作伙伴',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  4 => 
  array (
    'typeid' => '86',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '46',
    'name' => '探索您的机会',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  5 => 
  array (
    'typeid' => '1',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '1',
    'name' => '新闻',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '1',
    'description' => '新闻模型搜索',
  ),
);
?>